# Generated by Django 4.2.1 on 2023-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="testTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("date", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=10)),
                ("url", models.CharField(max_length=50)),
            ],
        ),
    ]
