# Generated by Django 4.2.1 on 2023-05-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BLOG", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="testTable",
            new_name="EventTable",
        ),
    ]
